name: converterpro
description: Unit and currencies converter
publish_to: none

version: 3.2.1+37

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # App dynamic color theme
  dynamic_color: ^1.5.4
  # Native splash screen on Android
  flutter_native_splash: ^2.2.16
  # App logo in drawer
  google_fonts: ^3.0.1
  # Navigation
  go_router: ^5.2.4
  # Translations
  intl: ^0.17.0
  # State management
  provider: ^6.0.3
  # Android app shortcuts
  quick_actions: ^1.0.0
  # Store the customizations and the latest currencies convertions
  shared_preferences: ^2.0.15
  # Unit conversion
  units_converter: 2.0.1
  # Open external pages such as GitHub repo, Play Store, etc
  url_launcher: ^6.1.5
  # Resize window during testing
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  # Sub packages ---------------------------------------------------------------
  # Calculator widget and logic
  calculator_widget:
    path: packages/calculator_widget
  # Update the exchange rates
  exchange_rates:
    path: packages/exchange_rates
  # App translations
  translations:
    path: packages/translations

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1
  msix: ^3.6.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_native_splash:
  # Run code generation: `flutter pub run flutter_native_splash:create`
  web: false
  color: "#eeeeee"
  color_dark: "#333333"
  image: resources/splash/splash.png

msix_config:
  display_name: Converter NOW
  publisher_display_name: Damiano Ferrari
  identity_name: 39826DamianoFerrari.ConverterNOW
  logo_path: resources\images\logo.png
  output_name: converternow-windows
  publisher: CN=E8FE6044-F04C-422E-AC68-EDA83F6AAFB2
  capabilities: internetClient

flutter:
  uses-material-design: true
  generate: true
  assets:
        - resources/images/
